Removed ==0.10 on Flask due to errors.
With Flask==0.10, running gives:
ImportError: cannot import name exceptions

Removing the version requirement fixes this.